kits-ab/LogLady

README.md, docs/ADR/0002-use-gitflow-and-naming.md
#5 update README and ADR. Explained naming, gitflow, task ID
=> #5 update README and ADR. Explained naming, gitflow, task ID

package.json, public/electron.js
=> #8 add support for autoupdate

src/fileReader.js
#26 Modified functions, made readNthLines async and exported functions.
=> #26 Modified functions, made readNthLines async and exported functions.

public/electron.js, src/js/engine/engine.js, src/js/view/App.js, src/js/view/menu.js
=> Feature/get filepath from opendialog #45

src/js/engine/engine.js, src/js/view/App.js, src/setupTests.js
=> #51 - add once on listeners and changed a few names

package.json
=> #47 packaging should now work

package.json, src/js/view/components/LogViewer.js, src/js/view/components/LogViewer.test.js, src/setupTests.js
=> #66 - change color on highlight

package.json, src/js/view/App.js, src/js/view/components/LogViewer.js
=> Feature/some design #83

.travis.yml
=> trying to add stuff for release

.env, .travis.yml
=> test stuff for release

.env, .travis.yml, package.json
=> Feature/travis conf #75

src/js/engine/engine.js, src/js/view/App.js, src/js/view/components/StatusBar.js, src/js/view/ipcListener.js, src/js/view/reducers/index.js, src/js/view/reducers/logInfoReducer.js
=> #155 statusBar to redux

src/js/view/App.js, src/js/view/actions/dispatchActions.js, src/js/view/components/LogViewer.js, src/js/view/components/StatusBar.js, src/js/view/components/TopPanel.js, src/js/view/reducers/index.js, src/js/view/reducers/topPanelReducer.js
=> Feature/top panel to redux #149

package.json, src/js/engine/engine.js, src/js/view/App.js, src/js/view/components/LogViewer.js, src/js/view/components/StatusBar.js, src/js/view/components/TabSettings.js, src/js/view/ipcListener.js, src/js/view/ipcPublisher.js, src/js/view/reducers/index.js, src/js/view/reducers/logViewerReducer.js
=> Feature/logviewer to redux #152

src/js/view/App.js, src/js/view/ipcListener.js
=> #138 Filepath is redux

src/js/adapters/fileReader.js
=> #144 refactor fileReader

src/js/adapters/fileReader.js, src/js/electron/menu.js, src/js/engine/engine.js, src/js/view/ipcListener.js, src/js/view/ipcPublisher.js
=> #147 refactor engine

docs/ADR/0003-implement-redux.md, docs/ADR/0004-implement-styled-components.md
=> #163 adr redux and styled-components

src/js/view/App.js, src/js/view/components/LogViewer.js, src/js/view/components/StatusBar.js, src/js/view/components/TabSettings.js, src/js/view/components/TopPanel.js, src/js/view/styledComponents/AppStyledComponents.js, src/js/view/styledComponents/LogViewerStyledComponents.js, src/js/view/styledComponents/StatusBarStyledComponents.js, src/js/view/styledComponents/TabSettingsStyledComponents.js, src/js/view/styledComponents/TopPanelStyledComponents.js
=> Feature/refactor to styled components #139

package.json, public/electron.js, src/js/view/styledComponents/AppStyledComponents.js, src/js/view/styledComponents/LogViewerStyledComponents.js, src/js/view/styledComponents/StatusBarStyledComponents.js, src/js/view/styledComponents/TabSettingsStyledComponents.js, src/js/view/styledComponents/TopPanelStyledComponents.js
=> Feature/save window state #141

src/js/electron/menu.js
=> #168 cancel works in dialog and added short command on open file

public/electron.js
=> #183 set minWidth and minHeight of main window

src/js/view/components/LogViewer.js
=> #201 Text color work with background on highlight

package.json, src/js/view/components/LogViewer.js, src/js/view/components/TextHighlightRegex.js
This pull request will make it so that text matched in a line is highlighted separately.
Highlighted text is refactored into its own component.
=> #180 Feature/highlight matched text

src/js/view/components/LogViewer.js, src/js/view/styledComponents/LogViewerStyledComponents.js
=> #109 reduce spacing and no line breaks

src/js/view/App.js
This pull request will remove the extra call to ipcListener in App.js on startup
=> Hotfix away double listeners on startup

public/electron.js
#212 devTools now only available in dev-mode
=> #212 devTools now only available in dev-mode

src/js/view/components/StatusBar.js, src/js/view/components/TopPanel.js
change tail to follow & path to file in gui bc it makes more sense at the moment
=> change tail to follow & path to file in gui bc it makes more sense

public/electron.js, src/js/view/styledComponents/common/InputStyledComponents.js, src/resources/loadingSpinner.html
do we really need a spinner on startup?
=> Feature/add splash screen #220

public/electron.js, src/js/view/components/StatusBar.js
=> #238 complete path in tooltip and three last in statusbar

src/js/view/components/helpers/lineFilterHelper.js
=> #240 no longer crash when faulty regular expresion in filter

src/js/view/reducers/settingsReducer.test.js
=> Feature/add test for settings reducer #244

index.html
=> #260 add info on regex and highlight to product-page

src/js/adapters/fileReader.js, src/js/view/AppContainer.js, src/js/view/ipcListener.js
=> #223 Potential open file is closed before a new file is opened.

package-lock.json, src/js/view/AppContainer.js, src/js/view/configurations/configureStore.js, src/js/view/configurations/configureStore.test.js, src/js/view/ipcListener.js
Hela `configureStore.js` var beroende av att `store` var satt från sidan (`setStore`). Därför är ett mönster att innesluta alla funktioner i en "övre" funktion som tar emot `store` och sedan returnerar de funktioner ni behöver använda på olika ställen.
Tog även med `send`-parametern som default inparameter så den går att mocka enkelt när man vill skriva enhetstester.
=> Dependency injection and test

src/js/electron/menu.js
This pull request will make it so that the file selected in the recent files sub menu is opened when clicked.
=> #282 Make recent files great again

src/js/view/components/LogViewer.js, src/js/view/components/helpers/regexHelper.js, src/js/view/components/helpers/regexHelper.test.js
=> Feature/text default on regex #261

src/js/view/components/TopPanel.js, src/js/view/styledComponents/TopPanelStyledComponents.js
=> #289 changed text to logotext

src/js/adapters/fileReader.js
=> #277 Starts fs.watch on mac/linux and fs.watchFile on windows.

src/js/view/components/StatusBar.js, src/js/view/components/helpers/StatusBarHelper.js, src/js/view/components/helpers/statusBarHelper.test.js
#286 
fixed filepath on windows
=> Bug/filepath on windows #286

src/js/view/components/SnackBar.js, src/js/view/styledComponents/common/FlexBoxStyledComponents.js, src/js/view/styledComponents/common/SnackBarStyledComponents.js
=> #300 fix the size on snackbar

src/js/engine/engine.js, src/js/view/App.js, src/js/view/components/LogViewer.js, src/js/view/components/SnackBar.js, src/js/view/components/StatusBar.js, src/js/view/components/TabSettings.js, src/js/view/components/TopPanel.js, src/js/view/configurations/configureStore.js, src/js/view/configurations/configureStore.test.js, src/js/view/reducers/index.js, src/js/view/reducers/menuReducer.js, src/js/view/reducers/settingsReducer.js, src/js/view/reducers/topPanelReducer.js
This pull request will rename all the states produced by the reducers to state as recommended by the redux manual.
=> Refactor reducer state names

src/js/electron/menu.js
=> #308 added copy to menu and functionality on mac

public/electron.js, src/js/engine/engine.js, src/js/view/App.js, src/js/view/actions/dispatchActions.js, src/js/view/components/TabPanelContainer.js, src/js/view/components/helpers/handleFileHelper.js, src/js/view/ipcListener.js, src/js/view/reducers/logInfoReducer.js, src/js/view/reducers/logViewerReducer.js, src/js/view/reducers/menuReducer.js, src/js/view/styledComponents/TabPanelStyledComponents.js
This pullrequest will add support for several open files, both in the backend and frontend. PR #323 has been merged intot this branch, so approving this PR means that #323 can be removed.
=> Support several files in both GUI & backend #225 #226

.travis.yml, package.json
Update version to see if this stops deployment from breaking
=> #221 Fix windows code signing

.travis.yml, package-lock.json, package.json
I have configured Travis to sign the application for macOS, and during my test run it seemed okay. 
As a new release is in order, the version needs to be updated - that's what I have done in this PR!
=> #206 Update version of application and files after Travis build

package-lock.json
Updated security found by `npm audit` by running `npm audit fix`.
=> #349 Fix security issues with npm audit fix

docs/ADR/0005-use-of-fabric-ui-as-design-system.md
Created a quick ADR for our decision to use a design system.  
I don't know if more context is needed, or if the decision needs to be motivated more.   
I am also unsure about what to write in consequences, as it feels weird to try to predict the future, but maybe it should just contain what we believe the consequences will be?
Feedback is appreciated!
=> #334 Create adr for use of design system

package-lock.json, package.json, src/js/view/AppContainer.js
Added Fabric UI to project, to avoid everyone having to install it separately and to avoid annoying merges with package/package-lock.
=> #334 Add Fabric UI to project

.travis.yml, package-lock.json, package.json, src/js/engine/engine.js
* Updated Electron to v7.1.2
* Fixed an issue where nothing happened when opening a file after updating
* Incremented app version
I incremented the app version as I think a new release is in order! What do you think?
=> #362 Update Electron and increment app version

public/notarization/notarize.js
A very simple PR, that's why I labelled it a hotfix.
* Added a check for environment variable TRAVIS_PULL_REQUEST and if present notarization is skipped. According to Travis docs it is a boolean, but I handle it as truthy/falsy.
* Did some cleaning and moving around in the code to make the code more legible and stable
=> #373 Added PR skip for notarize.js

src/js/electron/menu.js
I simply changed the link from Akars consultant profile to LogLadys website, no major changes required.
=> #388 Update destination for 'Learn more' link

README.md
#414
Wrote a quick draft of how to resolve issues with electron not displaying a window. I am not sure if current placement in the README is the most optimal, or if the wording is entirely clear. Suggestions for improvements are welcome.  
On another note, the README is getting pretty big. Maybe it's time to add a table of contents?
=> #414 First draft of troubleshooting help

src/js/view/components/TabPanelContainer.js, src/js/view/styledComponents/TabPanelStyledComponent.js
#416 
Made a quick swap of our custom `TabPanelContainer` for Fabric UI:s `Stack` while investigating #382.
=> Feature/implement fabric stack #416

src/js/view/components/LogViewer.js
#398 
Just removed the old close button, easy peasy.
=> #398 Removed old close button from LogViewer

src/js/view/actions/dispatchActions.js, src/js/view/components/LogViewer.js, src/js/view/components/StatusBar.js, src/js/view/components/TabSettings.js, src/js/view/components/TopPanel.js, src/js/view/components/common/buttons/SwitchButton.js, src/js/view/reducers/settingsReducer.js, src/js/view/reducers/settingsReducer.test.js, src/js/view/reducers/topPanelReducer.js
#224
This pull requests tracks top panel settings and tab settings on a per file basis. No GUI changes have been made yet as we wait on consensus as to what these changes should be.
=> #224 Settings for individual files 

src/js/adapters/fileReader.js, src/js/adapters/fileReader.test.js, src/resources/testFile
#440 
In this pull request `fileReader` gets the ability to read a file from a specified byte, and then read an amount of bytes onward. The first and last lines are assumed to be garbage and are thrown away, and the rest of the lines are returned, together with the byte where they start and the byte where they end.
=> #440 Read file from position

src/js/adapters/fileReader.js, src/js/engine/engine.js, src/js/view/actions/dispatchActions.js, src/js/view/components/LogViewer.js, src/js/view/components/LogViewerList.js, src/js/view/components/helpers/handleFileHelper.js, src/js/view/components/helpers/logHelper.js, src/js/view/ipcListener.js, src/js/view/reducers/logViewerReducer.js, src/js/view/reducers/logViewerReducer.test.js, src/js/view/styledComponents/LogViewerListStyledComponents.js
#443 
Enormous pull request containing the MVP for the scrollback feature. Check that everything works on your machine and feels reasonably good to use, and we'll refine the experience in the coming sprints.
=> #443 Feature - gui scrollback

src/js/hiddenWindow/mainScriptOffloader.js, src/js/view/components/LogViewerList.js, src/js/view/components/SingleLogLine.js, src/js/view/components/TextHighlightRegex.js
I didn't like the solution I did some time ago, and decided to improve it a tiny bit. The code is a bit more legible, and performance might be better since the renderers for a log line no longer uses Regular Expressions.
I update the mainScriptOffloader.js to send lines divided into sections as an array, with booleans to show whether they should be highlighted or not. The prior solution just sent a string with text added to do this, which wasn't perfect.
I updated the renderers to use the information sent for the lines to show them instead of determining stuff on it's own, which might improve performance a bit if it needs to re-render a lot of lines.
I tested it out on my end and everything worked the same as in develop branch, but please try it out on your computer!
=> Improve filtering and highlighting code

src/js/view/components/LogViewer.js, src/js/view/components/TabPanelContainer.js, src/js/view/reducers/logViewerReducer.js, src/js/view/styledComponents/LogViewerStyledComponents.js, src/js/view/styledComponents/TabPanelStyledComponent.js
For small sized files this will barely make a change, but if the file is big enough then the user will see a loading spinner with the text "Loading file" in the middle. The spinner will be there until the engine is done counting all the lines in the file, at which point it will be replaced by the lines in the file instead.
=> #512 Added spinner indicating file is loading
