package.json
src/js/view/components/LogViewer.js
src/js/view/components/TextHighlightRegex.js
src/js/view/components/helpers/regexHelper.js

This pull request will improve the performance of highlighting matches in text
Previously there was a dependency on a function in an external package for regex react replace but this was rather slow
Previously the text would create <span> tags around every match meaning that if you tried to highlight '.' then there would be created a span around every character in the text
This is resolved by making our own function (groupByMatches) that loops through a string that groups adjacent matched substrings together.  Then TextHighlightRegex renders each _group_ in separate spans. A '.' regex will instead create a single span around the whole string.

Fix/regex performance #215

---

src/js/electron/menu.js

#267 
When packaged reload and toggle development tools don't show.
Used roles instead of label after I read from electron docs: "It is best to specify role for any menu item that matches a standard role, rather than trying to manually implement the behavior in a click function. The built-in role behavior will give the best native experience."
further reading: https://electronjs.org/docs/api/menu-item
No test because isDev comes from electron-is-dev dependency therefore not ours to test

#267 reload and toggle development tools don't show in release

---

src/js/view/components/LogViewer.js
src/js/view/components/LogViewerList.js
src/js/view/components/helpers/cacheHelper.js
src/js/view/components/helpers/cacheHelper.test.js
src/js/view/components/helpers/measureHelper.js
src/js/view/components/helpers/measureHelper.test.js
src/js/view/styledComponents/LogViewerListStyledComponents.js
src/js/view/styledComponents/LogViewerStyledComponents.js

This pull request will fix the bug with sizing errors when wrapping lines and add caching for lines
Previously the height of the windowed list was calculated incorrectly when wrapping lines of different sizes as the heights would not be uniform. This is remedied by changing the type of the windowed list from 'uniform' to 'variable' and by calculating the height of each individual element.
To avoid rendering each element and then rendering each height one character is rendered that is then used to estimate the width and height of each element. As this is done mathematically for each element, it's quite performant. However doing this operation is _only_ necessary when resizing the window or if the content of the list is changed (ie: a filter is used) so caching for lines and their …

Fix/wrap lines variable height #272

---

src/js/view/App.js
src/js/view/actions/dispatchActions.js
src/js/view/components/SnackBar.js
src/js/view/components/common/snackbar/SnackBar.js
src/js/view/reducers/index.js
src/js/view/reducers/snackBarReducer.js
src/js/view/reducers/snackBarReducer.test.js
src/js/view/styledComponents/common/ButtonStyledComponents.js
src/js/view/styledComponents/common/FlexBoxStyledComponents.js
src/js/view/styledComponents/common/SnackBarStyledComponents.js

This pull request will add a snackbar component and reducer that can be called to show a snackbar with some kind of message (If you don't know what a snackbar is: https://www.polonel.com/snackbar/)
We could use this component to show relevant messages to the user, such as error messages
I've created two `SnackBar` components, one in `components/common` that is generic and one in `components` that uses the generic one but adds some extra functionality, like a dismiss button that dispatches a hide event.
If we so wish we could style the snackbar further in the future based  on importance level like https://codesandbox.io/s/5kq4jv6vpn but right now the styling is basic
*Motivation*
I tried opening a non-readable file in VS Code and they use a similar notification system
*How to use*
dispatch …

Add snackbar component, and add it to the app

---

public/electron.js
src/js/adapters/fileReader.js
src/js/electron/menu.js
src/js/engine/engine.js
src/js/view/App.js
src/js/view/actions/dispatchActions.js
src/js/view/components/LogViewer.js
src/js/view/components/LogViewerList.js
src/js/view/components/SnackBar.js
src/js/view/components/StatusBar.js
src/js/view/components/helpers/errorHelper.js
src/js/view/components/helpers/handleFileHelper.js
src/js/view/configurations/configureStore.js
src/js/view/configurations/configureStore.test.js
src/js/view/ipcListener.js
src/js/view/reducers/logInfoReducer.js
src/js/view/reducers/logViewerReducer.js
src/js/view/reducers/logViewerReducer.test.js
src/js/view/reducers/menuReducer.js
src/js/view/reducers/menuReducer.test.js
src/js/view/styledComponents/LogViewerStyledComponents.js
src/js/view/styledComponents/common/FlexBoxStyledComponents.js

This pull request will make it so that error messages show up as notifications in the frontend, but also change part of the structure of the backend.
Instead of passing a message to the frontend, and then back when opening a file, the file is opened in the backend and then the frontend is told that a file is opened. Then the frontend sends back a message to follow the file when done.
The gathering of file information (number of lines, end index and history) is now happening in one pass and splits on \r and \n. The lines are also sent as an array of strings than a string, that was split in the logViewer.
This pull request also contains some common styled components for using flexboxes.
As we only support one file at the moment opening a file has the special behaviour of closing watchers to …

#279 #280 Push file errors to the frontend

---

src/js/adapters/fileReader.js

There was a bug that if you had a file that was less than ten rows then the first row wasn't being read
This was caused by not adding all the unused characters if we hit the start of the file.

#304 Fix bug with the first row in a file not being added to the last N lines

---

src/js/view/components/LogViewerList.js
src/js/view/styledComponents/LogViewerListStyledComponents.js

This pull request will hide the x-axis scrollbar when wrapping lines. This will make it so the scrollbar doesn't show up on Windows, or any other platform as that is the intended behaviour when wrapping lines.

#299 Make it so that when wrapped the x-scrollbar is hidden

---

.travis.yml
package.json
src/js/view/components/LogViewer.js

I have identified what caused the problem that no new lines would be added and different tabs would show the same lines.
It was because I was using a stale props in my eventlistener, and making sure the source matched the one that was sent. I did this in preparation for multiple files as I thought there would be one LogViewer component for each open file - but that isn't the case currently.
In the future, when we try to have multiple tabs split in the window, this solution probably won't work - but that's what makes it a hotfix I guess 🤷‍♂
I tested it on my machine and it works as expected. Please try opening multiple files and adding lines to them on your end as well!

Hotfix for multiple files and hidden window offloader

---

package-lock.json
src/js/view/components/LogViewer.js

I have identified what caused the problem that sometimes duplicate lines would show up when a filter was set. I missed this while testing the filtering earlier.
The problem happens because I was using the state to determine what lines were new in order to only send those in the hook for when props.logs changes - but updating state happens asynchronously, so the state can't be relied on like that.
I fixed the problem by using a ref to keep track of the length of props.logs last time the hook was called. Ref is mutable, so I can rely on it to be correct for every call of the hook, and I update it using props.logs which the hook depends on to be fired. The ref is reset when a filter or highlight is changed, as the current logs will be wiped by that.
I also noticed that the version in …

Hotfix for duplicate lines while filtering

---

index.html

I checked earlier pull requests for the website, #293 , and hopefully I have done this right. I _think_ the latest version will be deployed automatically if this PR is merged. Note that this is a merge to branch gh-pages.
I have removed the static download links in the html-document and added a script that makes a request to GitHub API for download links from the latest release instead. It then presents the correct link based on OS, like earlier.
I also added a fallback to link to the latest release on GitHub if either the API can't be used or the OS can't be determined
The GitHub API serves the tag name, e.g. `v.1.1.2` and files are named with that version, e.g. `loglady-1.1.2.dmg`, but I decided to not use that. My script assumes there is one binary file for each OS and that the file …

#353 Update links for website

---

src/js/view/components/LogViewerList.js
src/js/view/components/SingleLogLine.js
src/js/view/styledComponents/LogViewerListStyledComponents.js

I have changed the list-component from react-window's VariableSizeList to Fabric UI's List. I was able to remove some code, mostly related to keeping track of the size of the VariableSizeList, which seems to be handled automatically by Fabric.
I also had to move the scrolling element to the list container, this was done simply by adding `overflow: auto` to the styled component.
Lastly, I had to change how the LogLine determines it's background color. Previously this was done using the nth-child CSS property, but Fabric UI wraps each list item in a list item container which made each LogLine be the first child, thus they all had the same background color. Now, I send the index of the item in datalist to the component, and the background color is based on that instead.

Feature/prototype fabric ui listview #365

---

.travis.yml
package-lock.json
package.json
public/notarization/entitlements.mac.plist
public/notarization/notarize.js

The second step for macOS code signing, notarizing the app!
It works on my machine and Gatekeeper accepts the app afterwards, and I hope it will work on Travis as well.
* Added package [electron-notarize](https://github.com/electron/electron-notarize). It's made by the team developing Electron
* Updated the config for electron-builder, as notarization adds a few requirements
* Added a script using electron-notarize, that electron-builder runs after it has signed the app
* Updated the macOS image to the latest version for Travis
I also have:
* Switched the certificate used for signing in Travis - I was using Apple Development when Developer Id should be used.
* Created a Application Id for the application, which is needed for notarization and distribution
* Added …

Feature/notarize macos app #206

---

.travis.yml
README.md
package.json

Another small PR! But this one should improve the process of creating a new release in the future - all that is needed now is to change the version in package.json!
* Added a new command to npm that returns the version number from package.json
* Updated Travis conf to export the result from the command above as an environment variable
* Updated Travis conf to use the environment variable to create a new tag and find the correct files to release
* Updated the README on how to make a new release
I have tried it out on a private repo and everything worked there, so it shouldn't be a problem for this repo.

#352 Simplify release process for Travis

---

public/notarization/notarize.js

#386 A quick hotfix for this bug.
When I wrote the script earlier I read the docs and thought that TRAVIS_PULL_REQUEST would be either the PR number or `false` - and as such I could use it as falsy.
Turns out that didn't work, and the docs actually mention the variable to `"false"` if build is not a PR. I have fixed this in this PR, but this also means that the latest release has not been notarized.

 #386 Update notarize.js to use env variable as a string

---

.travis.yml

#387 Another simple hotfix for a mistake I did 😬
This time, Travis was configured so the deploy stage was run on pull requests to master. This wasn't intended, only builds triggered by pushes to master should try to deploy. For pull requests and builds on develop only the package stage should run.
I fixed it by adding another conditional for if the build was triggered by a pull request, and if so deploy will be silently skipped.
The conditionals are designed to be opposite - if the package stage should run the deploy stage won't run and vice versa.

#387 Update Travis conf so deploy only runs on master builds

---

package-lock.json
package.json

#383 Cross-env is now used to set environment variables across platforms!
* Added [cross-env](https://www.npmjs.com/package/cross-env) as a dev dependency, it's a very popular package for doing this kind of thing
* Updated Husky hooks and npm scripts to use cross-env
Using this, the scripts and hooks should now work similarly across platforms 🙌

#383 Add cross-env for scripts and hooks

---

package-lock.json
package.json
src/js/view/components/TabPanelContainer.js

Closes #394
I have added keybinds for switching tabs, by using ctrl+tab to move to the right and ctrl+shift+tab to move to the left.
When I converted the note to an issue it says opened by me - which isn't correct, this was a great idea by Doverstav!
* Added package [mousetrap](https://www.npmjs.com/package/mousetrap), it's a simple library for keybinds with no dependencies. It made it easier to add keybinds with multiple keys and bind/unbind them within React
* Updated `TabPanelContainer.js` to register the keybinds, unbind when needed, and use a handler to know what tab to switch to. It uses the existing function `tabOnClick` to actually switch to the tab!

#394 Add hotkeys for switching tabs

---

src/js/view/styledComponents/AppStyledComponents.js

The root container component was displaying a vertical scrollbar due to the newly added 1 pixel top border.   
This border was deemed to be needed to create some separation between the menu and the top panel, so to remove this scrollbar but retain the top border, the box sizing of the root container was changed to `border-box`.   
This changes the size calculation of the box to include border and padding when calculation box size, which results in the vertical scrollbar disappearing.

#381 Set root container box-sizing to 'border-box'

---

public/notarization/notarize.js

#412 
See issue for more details. Short summary: The notarize script gets caught in an endless loop due to a boolean flag not being set correctly.  
I made a quick truthtable to show that the current conditional does not work:  
| shouldRun | waitingOutputRunning | shouldRun && !waitingOutputRunning         |
| --------- | -------------------- | ------------------------------------------ |
| T         | F                    | T                                          |
| F         | F                    | F                                          |
| T         | T                    | F                                          |
| F         | T                    | F (Will not stop running though it should) |
The suggested fix of turning it into an OR-expression won't work either, as …

#412 Fix notarize.js infinite loop

---

package-lock.json
src/js/view/components/LogViewer.js
src/js/view/styledComponents/TextHighlightRegexStyledComponents.js

Solved by adding the highlightColor prop to the array in useEffect in LogViewer.js
```
useEffect(() => {
/* Effect for when a new filter or highlight is applied,
send the lines to be filtered and highlighted again */
if (props.logs[props.source.path]) {
// Reset the previous lines count, as all lines should be wiped.
previousLinesLength.current = 0;
sendMessageToHiddenWindow({
logs: props.logs[props.source.path]
});
}
}, [props.filterInput, props.highlightInput, props.highlightColor]);
```

#399 Lines in logviewer now highlights when colors are chosen from the color picker

---

src/js/view/components/TabPanelContainer.js

Added a PivotItem with index="open-new-file-tab" and a check in the tabOnClick function where showOpenDialog() is called when index === 'open-new-file-tab.

#379 bug/Add missing open new file button in TabPanelContainer

---

src/js/adapters/fileReader.js
src/js/engine/engine.js

#434
Engine can now request text with position from adapter. It tries to do this in a smart way by estimating the bytes in a line and then fetch one screen behind and one screen ahead in order to build a buffer. If, for some reason, the lines are very long and not enough lines were returned in a single request, it will make more requests until it gets enough lines. The exception to this is if it reaches the end of the file, where it instead will stop requesting and return the lines it has gotten up until this point.
This pull request also fixes an issue in adapter with reading the last and first line of a file.

#434 Get text from position from adapter

---

src/js/view/reducers/menuReducer.js

The issue regarding the 0 appearing under tab when reduxState.json is empty seems to be solved when letting nextIndex in initialState start at 1 instead of 0. The issue still does not appear when reduxState.json is containing a saved state.

#447 Fix issue with number under tab

---

src/js/hiddenWindow/mainScriptOffloader.js

When replacing a line with a highlighted variant there seem to be some whitespace in the end and/or beginning of the last row, causing it to fail highlighting that row. By trimming line (at row 51) before using replace the last row appear to be highlighted correctly.

#453 Fix highlightning issue

---

src/js/adapters/fileReader.js
src/js/view/components/CustomScrollBar.js
src/js/view/components/LogViewer.js
src/js/view/components/LogViewerList.js
src/js/view/styledComponents/LogViewerListStyledComponents.js
src/js/view/styledComponents/LogViewerStyledComponents.js

- Moved the slider to its own file, named it CustomScrollBar and added some quick styling before positioning it by the logviewer. 
- I also renamed the slider code in the LogViewer to have names related to scroll instead of slider.   
-  Created a log viewer root container and placed the custom scroller next to the log viewer. It now stays where it should even when the lines are long. 
-  Added overflow-x: auto to the logviewer container to make the length of the file readable.
-  Finally some issues occurred when calculating the amount of lines to fill the viewer. It was based on offsetHeight. It did not take the horisontal scrollbar into account. I changed offsetHeight to clientHeight and it seems to be more accurate.

 #464 #461 Move slider to its own file and fix related bugs

---

src/js/view/components/LogViewer.js

#472 
I noticed the scroller behaved weirldy/badly with track pads, and this was because of the timeout to cancel was set inside the function to be called after the timeout, meaning that there was never a timeout to cancel, resulting in many reads and strange behavior.  
The bytes to read seemed to end up as fractions of a byte, which caused the read to misbehave, so I rounded to bytes to the nearest integer before sending a read request, which should fix some issues.  
Sadly, scrolling with a track pad is now largely feedback-less, but I think this is better than what we had before.
Initial behavior when scrolling with (my) track pad:
Behavior when correctly rounding bytes, but sending a lot of read requests, slowing things down. Note that somewhere around the middle I started scrolling …

#472 Round bytes to read to nearest integer, save timeout correctly

---

src/js/engine/engine.js
src/js/view/components/LogViewerList.js

Empty lines should be displayed correctly with props.lines going through a function before being assigned as itemData. Try it on your machine!

#459 Fix empty rows being displayed incorrectly

---

src/js/view/components/CustomScrollBar.js
src/js/view/components/LogViewer.js
src/js/view/reducers/logViewerReducer.js
src/js/view/reducers/logViewerReducer.test.js
src/js/view/reducers/topPanelReducer.js

In this pull request: 
- Added/adjusted some tests for the logViewerReducer.
- Instead of having the scroll position locking itself to the base when the file is running, it now toggles the tailswitch to off and enables scrolling again when using the wheel, trackpad or when clicking/dragging in the scroller. Toggling the follow switch to on will make it jump down to the tail and start following the running file again.
- Another proposed solution concerning the scrolling behavior when using the track pad or the mouse wheel. Instead of setting the new scroll position using the event.deltaY value, I tried it with a mean byte value of the lines. The deltaY still comes in handy when deciding if the position should increase or decrease. By moving the - value to either true or false, it seems …

#462 Fix of empty page when scroll position is 0 and a couple of proposed changes to enhance the scroll experience.

---

src/js/view/components/LogViewer.js

Quick fix for a little bug I found when using the touchpad and not the mouse for a change. Let me know if this works on your machines as well! 
Reproduce by having a file with rows long enough to summon the vertical scroll. The horizontal scroll should not move when you scroll vertically with the touchpad after this fix.

Bug/ vertical trackpad scroll is no longer triggering the custom scroll bar #490 

---

src/js/view/components/LogViewer.js

Adding an effect to catch the update of the minScrollPosition value and set it as the scroll position seems to take away the big jump the scroll makes when scrolling upwards for the first time. 
The 'jump' from the initial set of lines (10) to the first fetched list of lines, which has a calculation based on the number of lines in the viewer, is still there. I was not sure if this issue covers that as well. 
I suspect that the correct amount of initial lines to display will be easier to fix once the cache is implemented.
What do you think?

Fix initial scroll position #463

---

package-lock.json
package.json
src/js/view/components/TabPanelContainer.js
src/js/view/styledComponents/TabPanelStyledComponent.js

Updated logfile review activity orange point into more significant icon which is an Up/Down Arrow displays that the current log in review activity state and the number of lines increasing. The new icon is more significant than the orange point. Also the color of the new icon is regular with UI Design.
I implemented different icons as shown in the attached PoC, you can choose which one is better, either if i have to keep this Up/Down Arrow, either the loading circle, or if i have to change to color into orange or other colors.

Logfile review activity icon instead the orange point

---

src/js/view/components/LogViewerList.js

Toggling the wrap line on or off now triggers a re-render instantly.
The problem:
The prop change that happened when Wrap Line was toggled did not fire a re-render of the List.
Possible reason why:
The List element (used in LogViewerList) was only rendering the log lines upon a render call of itself (used via its prop onRenderCell), and the prop that changed was only listened to by the log line elements, hence it did not see any change and therefore it did not re-render.
The fix:
By creating a reference to the List object it was possible to use its forceUpdate-method to make it re-render itself when the prop changed.

#450 Wrap Lines not visible upon start

---

package.json
src/js/view/components/TabSettings.js
src/js/view/styledComponents/TextHighlightRegexStyledComponents.js

Implemented Fabric UI ColorPicker instead of Github ColorPicker, now the user has all RGB colors to use.

Implement fabric-ui color picker

---

src/js/hiddenWindow/mainScriptOffloader.js
src/js/view/components/LogViewerList.js
src/js/view/components/SingleLogLine.js
src/js/view/styledComponents/LogViewerListStyledComponents.js

The background in the log viewer is now as wide as the container itself or as wide as the longest line.
The problem:
When opening a file that contained one or more wider lines than the view was you could see that the background was not as wide as the longest line. Directly opening a new log file with lines shorter than the container would reveal that the size was still wrong but this time it had the width of the old log file. 
The solution:
The first part was to remove that we set the width manually in the styling of the Log Line-element. Not only did this calculated width come out wrong, it was not necessary since it could be solved with the right CSS code. With the styling 'display: inline-block' and 'min-width: 100%' on the fabric ui List that contained the Log Lines, the right …

#474 Background of files with long lines are set to the wrong size

---

src/js/engine/engine.js
src/js/view/actions/dispatchActions.js
src/js/view/components/LogViewer.js
src/js/view/ipcListener.js
src/js/view/reducers/logViewerReducer.js
src/js/view/reducers/logViewerReducer.test.js

This pr fixes the frontend behaviour of following a file, adapting it to the new frontend cache logic.
The toggle is set to false by default. Toggling it should jump you to the bottom of the file and lock the scrollbar there. You should be able to follow a smaller file, with the whole content in the frontend as well as a larger file with empty lines and loglines in the list.
If you want to scroll up again, toggle it to off manually. It mimics the behaviour in the latest release. I removed the auto toggle when scrolling to and from the bottom which caused some issues. 
Toggling to off and not keeping the scroller at the bottom when the list added rows, was one of them. I would like to figure out how to implement that, but decided to go for the simplest solution for now.

#505 Fix follow tail behaviour 

---

src/js/view/actions/dispatchActions.js
src/js/view/reducers/settingsReducer.js
src/js/view/reducers/topPanelReducer.js

When closing a file not all states was cleaned up and instead continued to have that file in their state. This is now fixed and will improve a minor bug where the state was saved to disk with an often wrong state which led to the wrong files reopening.

#475 Clean the state in settings and topPanel when closing a file

---

src/js/adapters/fileReader.js
src/js/engine/engine.js
src/js/hiddenWindow/mainScriptOffloader.js
src/js/hiddenWindow/mainScriptOffloader.test.js
src/js/view/actions/dispatchActions.js
src/js/view/components/LogViewer.js
src/js/view/components/LogViewerList.js
src/js/view/components/TopPanel.js
src/js/view/components/common/input/TextFieldInput.js
src/js/view/components/helpers/logHelper.js
src/js/view/ipcListener.js
src/js/view/reducers/logViewerReducer.js
src/js/view/reducers/logViewerReducer.test.js

Before this PR only the lines from the cache were being sent through the mainScriptOffLoader for filtering and highlighting. To be able to filter through all the lines in a file,  the parts regarding filtering in the mainScriptOffLoader has been moved to engine. A function to fetch filtered lines has been added to the front-end and is called when the filterInput is not empty. 
See how this works for you, and do write any feedback you might have :).

#460 Fix filtering issue

---

.env
README.md
src/js/engine/engine.js
src/js/view/configurations/configureStore.js
src/js/view/configurations/configureStore.test.js

We identified this behaviour to be caused by the app trying to load the saved state in reduxState.json. topPanelState and settingsState changed between v.1.2.0 and 1.3.0 when the feature for individual setting for each file was implemented. If the user has the previous object in their reduxState.json the app will not work.
This solution simply adds a version check before loading the state from the disc. The object in reduxState.json is now saved with the current version in a key. 
Let me know how it works for you! Try it out by altering or removing the version value in your reduxState.json.

Fix bug that causes Loglady to freeze when opening a file in the new version #526

---

src/js/engine/engine.js
src/js/view/components/helpers/handleFileHelper.js

This small fix adds a request to the backend when a tab is closed for removing the cached lines of the closed file. That way it does not take up unnecessary space when it's not needed.

Flush backend cache for one file when closing its tab #527 

---

public/electron.js
src/js/engine/engine.js
src/js/view/components/helpers/handleFileHelper.js
src/js/view/ipcListener.js

Due to what seems like a race condition, the state was not always saved to the disc when closing the application. 
In this fix I trigger saving of the state when opening a file and when closing a tab, to really make sure that the reduxState.json contain the information of what tabs should be opened next time the application is started. Is it a little overkill? Perhaps? Maybe it is enough with just saving it on either of the cases? 
I also changed the name of the 'QUIT' case in ipcListener to 'SAVE_CURRENT_STATE'. It felt odd sending a quit message when opening a file and closing a tab.
Let me know what you think and if it works for you.

#531 BUG/ Save state to disc is sometimes not executed on quitting the application
